$axure.loadCurrentPage({
  "url":"iphone6.html",
  "generationDate":new Date(1550804752137.18),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"9b9551d7097e4c8fb67a2b2e495256b7",
    "type":"Axure:Page",
    "name":"iphone6",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"22de1212197b4522a3237b82be447e97",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFEEEBEE},
            "location":{
              "x":470,
              "y":244},
            "size":{
              "width":435,
              "height":886},
            "cornerRadiusTopLeft":"77"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"795d41dd0e7b432485ec4f5be143d05a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFEEEBEE},
                "location":{
                  "x":470,
                  "y":244},
                "size":{
                  "width":435,
                  "height":886},
                "cornerRadiusTopLeft":"77"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/iphone6/u0.png"}},
{
          "id":"9b82938025e247738bf0d5a44891288f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":500,
              "y":364},
            "size":{
              "width":375,
              "height":667}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"66c4566327b543b4b70bf554e09e7ae5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":500,
                  "y":364},
                "size":{
                  "width":375,
                  "height":667}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/iphone6/u2.png"}},
{
          "id":"c1af6405491f49598493b88f96ec3f04",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF999999},
            "location":{
              "x":680,
              "y":285},
            "size":{
              "width":15,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9b01d83eec6c48dbac6f25d69a23f99f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "location":{
                  "x":680,
                  "y":285},
                "size":{
                  "width":15,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/iphone6/u4.png"}},
{
          "id":"9873ccc0e5384c6187aa447d3f7ec40e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF999999},
            "location":{
              "x":625,
              "y":310},
            "size":{
              "width":10,
              "height":10},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"09e5a94632d74cf09bba949c10b23fcc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "location":{
                  "x":625,
                  "y":310},
                "size":{
                  "width":10,
                  "height":10},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/iphone6/u6.png"}},
{
          "id":"2dd5a07525cc450889b857c4a8188130",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF666666},
            "location":{
              "x":655,
              "y":310},
            "size":{
              "width":68,
              "height":10},
            "cornerRadiusTopLeft":"12"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fb1a2bafca7c4ab0bafa0dc0d5b506e0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF666666},
                "location":{
                  "x":655,
                  "y":310},
                "size":{
                  "width":68,
                  "height":10},
                "cornerRadiusTopLeft":"12"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/iphone6/u8.png"}},
{
          "id":"e31004ed9e5b48d386399ecc82c74eff",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":653,
              "y":1041},
            "size":{
              "width":70,
              "height":70}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5559e1ca908f403b9a31aefe9b630a75",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":653,
                  "y":1041},
                "size":{
                  "width":70,
                  "height":70}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/iphone6/u10.png"}},
{
          "id":"d69194b1ace346c3ac5412c08342d8e6",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF999999},
            "location":{
              "x":465,
              "y":445},
            "size":{
              "width":5,
              "height":65},
            "cornerRadiusTopLeft":"3"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d8733cb7b6294b2587d7edd40b12db63",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "location":{
                  "x":465,
                  "y":445},
                "size":{
                  "width":5,
                  "height":65},
                "cornerRadiusTopLeft":"3"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/iphone6/u12.png"}},
{
          "id":"98db08f6b03c4a4dbf63ee40c0fff1c3",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF999999},
            "location":{
              "x":465,
              "y":520},
            "size":{
              "width":5,
              "height":65},
            "cornerRadiusTopLeft":"3"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cc763f77cfbc4577a9f82c66183732e8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "location":{
                  "x":465,
                  "y":520},
                "size":{
                  "width":5,
                  "height":65},
                "cornerRadiusTopLeft":"3"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/iphone6/u12.png"}},
{
          "id":"9f3d8ca223994836aadef9d2d75d11f8",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF999999},
            "location":{
              "x":465,
              "y":390},
            "size":{
              "width":5,
              "height":35},
            "cornerRadiusTopLeft":"3"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d141b90185c94ee1a8e4236ee62a42e0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "location":{
                  "x":465,
                  "y":390},
                "size":{
                  "width":5,
                  "height":35},
                "cornerRadiusTopLeft":"3"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/iphone6/u16.png"}},
{
          "id":"658560859675437b94cf2855d3933ac2",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF999999},
            "location":{
              "x":905,
              "y":455},
            "size":{
              "width":5,
              "height":65},
            "cornerRadiusTopLeft":"3"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"585ab138d0a241fa94165fd3973d9f95",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "location":{
                  "x":905,
                  "y":455},
                "size":{
                  "width":5,
                  "height":65},
                "cornerRadiusTopLeft":"3"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/iphone6/u12.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "22de1212197b4522a3237b82be447e97":{
      "scriptId":"u0"},
    "795d41dd0e7b432485ec4f5be143d05a":{
      "scriptId":"u1"},
    "9b82938025e247738bf0d5a44891288f":{
      "scriptId":"u2"},
    "66c4566327b543b4b70bf554e09e7ae5":{
      "scriptId":"u3"},
    "c1af6405491f49598493b88f96ec3f04":{
      "scriptId":"u4"},
    "9b01d83eec6c48dbac6f25d69a23f99f":{
      "scriptId":"u5"},
    "9873ccc0e5384c6187aa447d3f7ec40e":{
      "scriptId":"u6"},
    "09e5a94632d74cf09bba949c10b23fcc":{
      "scriptId":"u7"},
    "2dd5a07525cc450889b857c4a8188130":{
      "scriptId":"u8"},
    "fb1a2bafca7c4ab0bafa0dc0d5b506e0":{
      "scriptId":"u9"},
    "e31004ed9e5b48d386399ecc82c74eff":{
      "scriptId":"u10"},
    "5559e1ca908f403b9a31aefe9b630a75":{
      "scriptId":"u11"},
    "d69194b1ace346c3ac5412c08342d8e6":{
      "scriptId":"u12"},
    "d8733cb7b6294b2587d7edd40b12db63":{
      "scriptId":"u13"},
    "98db08f6b03c4a4dbf63ee40c0fff1c3":{
      "scriptId":"u14"},
    "cc763f77cfbc4577a9f82c66183732e8":{
      "scriptId":"u15"},
    "9f3d8ca223994836aadef9d2d75d11f8":{
      "scriptId":"u16"},
    "d141b90185c94ee1a8e4236ee62a42e0":{
      "scriptId":"u17"},
    "658560859675437b94cf2855d3933ac2":{
      "scriptId":"u18"},
    "585ab138d0a241fa94165fd3973d9f95":{
      "scriptId":"u19"}}});